### ISSUE TITLE
Version check does not seem to work properly

### ISSUE THREAD

**Issue by tbekolay** [jellyfin/jellyfin-androidtv#1162]
**Describe the bug**
After my TV updated Jellyfin, I can no longer connect to my server. It gives me the following message:

> Server needs to be updated. Current version is 10.7.0 but app requires 10.7.0.0 or newer

I am using the `jellyfin/jellyfin` docker image on my server and I have pulled the latest version. This feels like an issue with parsing the version string?

**To Reproduce**
I am using the docker-compose install instructions from the official wiki's installation instructions. My docker-compose.yml is not special:

```
version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: "host"
    volumes:
      - /home/me/jellyfin/config:/config
      - /home/me/jellyfin/cache:/cache
      - /media/data/Media:/media/data:ro
    restart: "unless-stopped"
```

I installed the Android TV app from the app store and it automatically updated itself, I have not done anything special on my TV.

**Expected behavior**
Seems like version 10.7.0 should be >= 10.7.0.0

**Logs**
Nothing stands out to me looking through the logs, but if there's additional debug logging I can enable let me know.

**Screenshots**

![PXL_20211001_034816935](https://user-images.githubusercontent.com/203709/135562486-e220c77e-5f24-4f9c-ba03-705d99df3dd3.jpg)

**System (please complete the following information):**
 - Android TV or Fire TV version: Android 9
 - Device manufacturer: Sony
 - Device model: Bravia XBR-65X950H
 - Jellyfin server version: 10.7.0
