### ISSUE TITLE
The image does not display properly

### ISSUE THREAD

**Issue by tgdh520** [jellyfin/jellyfin-androidtv#4379]
### Describe the bug

jellyfin-androidtv installed on ThundeaL Projector TD80W Android 13 system does not display pictures, these pictures can be displayed briefly when the cursor is moved, but not when the cursor is stopped moving![Image](https://github.com/user-attachments/assets/97e736b4-3b7f-465a-bdbd-656cfa880a31)

### Application version

0.18.3

### Where did you install the app from?

None

### Device information

ThundeaL Projector TD80W

### Android version

android 13

### Jellyfin server version

10.10.3

**Comment by nielsvanvelzen** [comment]
When the images are not loading this is most likely some kind of network issue. Please try clearing the app cache and restarting your device to see if that fixes the issue. Additionally, if you use any kind of reverse proxy check the access logs.

**Comment by ad6922** [comment]
I’m experiencing a similar issue when installing Jellyfin v0.18.4 on a new Firestick for a family member. While all videos play and movie metadata load correctly, no images are displayed.

I’ve cleared the cache, removed the data, and even performed a factory reset as an additional step.

My setup includes running Jellyfin through NordVPN Meshnet, and this issue hasn’t occurred previously. After conducting some tests, I discovered that rolling back to Jellyfin v0.18.0-beta.2 resolves the problem, with images displaying properly. However, any version above this does not load images.

I also tested this setup locally, and the images load correctly when NordVPN is disabled. Unfortunately, I haven’t been able to find any relevant logs from NordVPN.

Any assistance would be greatly appreciated!

**Comment by tla44** [comment]
Same issue on 0.18.4. Images load when connecting via the android app and direct to server. But do not want to load on the Fire Stick. Have tried refreshing metadata, deleting metadata folder, reinstalling jellyfin on fire stick, updating server to 10.10.3.

**Comment by tla44** [comment]
Now works after deleting all data from the server (metadata, images, database, everything) and re creating the container (running in docker). The Fire TV version couldn't seem to pull the images correctly without this step - the Android version had no issues.

**Comment by Jellyboi420** [comment]
Same issue here, only on Fire Stick version as well. None of the other clients are affected. Can't be a network issue then.

**Comment by hakkabara** [comment]
same here.
tested on two firetv sticks my own server and the demo.jellyfin.org/stable server.
also cleared data, cache and uninstalled.

I also reinstalled the fresh apk from github via ADB.

all other clients Smartphone, Windows, Mac, Browser and the App on my Nvidia Shield are working

**Comment by hakkabara** [comment]
Also  tried older versions like v0.18.0 and v0.18.3 seems not working either

**Comment by gsilski** [comment]
This issue only occurs on FireTV sticks for me as well. Accessing the web browser version of Jellyfin over the same VPN on a cell phone shows all the images. The FireTV sticks on clients that are not on a VPN show images while those that are remote and on VPN do not show images.

**Comment by aldo-moreno-leon** [comment]
I have a GoogleTV with Android 12 and this issue is occurring me as well.
![PXL_20250207_084728130.jpg](https://github.com/user-attachments/assets/adce1d45-9f8e-4461-8163-337fccb5267d)

**Comment by simonm** [comment]
I get the same issue of no thumbnails or images using a fresh docker container using docker NFS volume mounts to the media (NFSv4). All content plays without issue, just no thumbnails or other content-related graphics in the app.

I only see this problem on an AndroidTV client. Web clients all seem to work without issue.

I've moved the container round to different servers. I also have this problem when running the container on the NAS host, so using local directories (and maybe eliminating NFS as a cause).

Docker compose is as in docs:

```
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1026:65536
    group_add:
      - "103"
    network_mode: 'host'
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - nfs_Movies:/Movies
      - nfs_TV:/TV
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://<local network ip>
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
volumes:
  nfs_Movies:
      driver: local
      driver_opts:
        type: nfs
        o: nfsvers=4,addr=server_name,rw,vers=4.1
        device: ":/foo/bar/baz/movies"
  nfs_TV:
      driver: local
      driver_opts:
        type: nfs
        o: nfsvers=4,addr=server_name,rw,vers=4.1
        device: ":/foo/bar/baz/tv"
```
